site_name: SentinelStacks Documentation
site_description: Documentation for the SentinelStacks AI Agent Management System
site_author: SentinelStacks Team
repo_url: https://github.com/sentinelstacks/sentinel
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - content.tabs.link

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Commands:
    - Overview: commands/index.md
    - Core Commands:
      - Init: commands/init.md
      - Build: commands/build.md
      - Run: commands/run.md
      - Version: commands/version.md
    - Agent Management:
      - PS: commands/ps.md
      - Stop: commands/stop.md
      - Logs: commands/logs.md
    - Image Management:
      - Images: commands/images.md
      - Pull: commands/pull.md
      - Push: commands/push.md
    - Registry Management:
      - Login: commands/login.md
      - Logout: commands/logout.md
    - Interaction:
      - Chat: commands/chat.md
      - Shell: commands/shell.md
    - Orchestration:
      - Stack: commands/stack.md
  - Architecture:
    - Overview: architecture/README.md
    - System Design: architecture/system_design.md
    - API Reference: architecture/api-reference.md
    - Sentinelfile Specification: architecture/sentinelfile_spec.md
    - Stackfile Specification: architecture/stackfile_spec.md
    - Shim Architecture: architecture/shim_architecture.md
    - Visualizations: visualizations/README.md
  - User Guides:
    - Getting Started: user-guides/README.md
    - Quick Start: user-guides/quick_start.md
    - LLM Providers: user-guides/llm_providers.md
    - Advanced Agents: user-guides/advanced_agents.md
    - Registry Management: user-guides/registry_guide.md
    - Multimodal Support: usage/multimodal.md
  - Examples:
    - Basic Chatbot: examples/chatbot.md
    - Research Assistant: examples/research-assistant.md
    - Team Collaboration: examples/team-collaboration.md
    - Financial Advisor: examples/finance-advisor.md
    - NLP Generator: examples/nlp-generator.md
  - Development:
    - Git Strategy: development/git_strategy.md
  - Planning:
    - Roadmap: planning/roadmap.md
    - Progress Tracker: planning/progress_tracker.md
    - CLI Implementation: planning/cli_implementation.md
    - Shim Implementation: planning/shim_implementation.md
    - Multimodal Support: planning/multimodal_support.md 