name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'scripts/generate_api_docs.sh'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install pyyaml
          
      - name: Generate API documentation
        run: |
          chmod +x scripts/generate_api_docs.sh
          ./scripts/generate_api_docs.sh
          
      - name: Copy API directory
        run: |
          mkdir -p docs/api
          cp -n scripts/api_index_template.md docs/api/index.md || true
          
      - name: Build MkDocs site
        run: mkdocs build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true  # Use a single commit for gh-pages
          commit_message: "Deploy documentation: ${{ github.event.head_commit.message }}" 